title: Samantha's Coding Page
author: CoderSam1088
email: CoderSam1088@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my site that I created while learning to use git.
  I am using terminal, but the instructions are using github

# social links
twitter_username: cruzteach  # DO NOT include the @ character, or else the build will fail!
github_username:  CoderSam1088  # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
